spring:
  datasource:
    url: jdbc:mysql://192.168.1.23:3306/java_web?useSSL=false&characterEncoding=utf-8&useUnicode=true
    username: root
    password: ssf971114
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
