spring:
  datasource:
    url: jdbc:mysql://192.168.1.24:3306/java_web?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: ssf971114
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true

